### ISSUE TITLE
Changes to get this to work (on linux, at least)

### ISSUE THREAD

**Issue by shirleyquirk** [ctag-fh-kiel/isf-glfw-example#1]
A) thank you so much for putting this together, i was really struggling to find any documentation on how to get VVISF to work with SDK_GLFW.  

when i compile this out of the box, i dont know why, but the displayScene renders red over the whole window fine,
but the isfScene only renders over the top right quarter of the window.  

furthermore, the isfScene renders only one texel across that quadrant, because `targetTex->glReadySrcRect()` is {(0,0),(1x1)} 
if  i leave tmpRect unmodified when setting up the texs array, it works as expected (i.e. i can see the full shader, but still just on that top right quadrant)

i cant figure out why the isfScene is rendering over a quarter of the screen;  what i did was to use isfScene for everything (i.e s/displayScene/isfScene/g ) .  

you still need to call render() again after rendering to a texture buffer, which doesnt feel right, (and kills my fps)
but as a workaround i save the callback lambda to a variable; and every frame i 
```setRenderCallback(nullptr);
targetTex = isfScene->createAndRenderABuffer(size);
setRenderCallback(renderCallback);
isfScene->render();
```
equivalently one could set targetTex to null, or maybe if one could access GLScene::_renderTarget from within the callback one could get away with a single invocation idk.

i dont know why these changes were necessary, i havent tried this on osx yet

**Comment by ctag-fh-kiel** [comment]
Thanks!
